// Generated by gencpp from file mavros_msgs/CommandBoolResponse.msg
// DO NOT EDIT!


#ifndef MAVROS_MSGS_MESSAGE_COMMANDBOOLRESPONSE_H
#define MAVROS_MSGS_MESSAGE_COMMANDBOOLRESPONSE_H


#include <string>
#include <vector>
#include <map>




namespace mavros_msgs
{
    class CommandBoolResponse
    {
    public:
        CommandBoolResponse() : success(false), result(0) {};
        CommandBoolResponse(const CommandBoolResponse& _alloc) : success(false), result(0) {};

        int success;
        int result;

        typedef mavros_msgs::CommandBoolResponse* Ptr;
        typedef mavros_msgs::CommandBoolResponse* ConstPtr;
        typedef mavros_msgs::CommandBoolResponse* CommandBoolResponsePtr;
        typedef mavros_msgs::CommandBoolResponse* CommandBoolResponseConstPtr;

        std::ostream& operator<<(std::ostream& s)
        {

            return s;
        };
        bool operator==(const ::mavros_msgs::CommandBoolResponse& rhs)
        {
            return this->success == rhs.success &&
                this->result == rhs.result;
        };
        bool operator!=(const ::mavros_msgs::CommandBoolResponse& rhs)
        {
            return !(*this == rhs);
        };
    }; // struct CommandBoolResponse_
} // namespace mavros_msgs


#endif // MAVROS_MSGS_MESSAGE_COMMANDBOOLRESPONSE_H
