// Generated by gencpp from file mavros_msgs/CommandBool.msg
// DO NOT EDIT!


#ifndef MAVROS_MSGS_MESSAGE_COMMANDBOOL_H
#define MAVROS_MSGS_MESSAGE_COMMANDBOOL_H


#include <mavros_msgs/CommandBoolRequest.h>
#include <mavros_msgs/CommandBoolResponse.h>

#include "../std_msgs/Msg.h"

namespace mavros_msgs
{

struct CommandBool : Msg
{

typedef CommandBoolRequest Request;
typedef CommandBoolResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CommandBool
} // namespace mavros_msgs



#endif // MAVROS_MSGS_MESSAGE_COMMANDBOOL_H
