// Generated by gencpp from file mavros_msgs/ManualControl.msg
// DO NOT EDIT!


#ifndef MAVROS_MSGS_MESSAGE_MANUALCONTROL_H
#define MAVROS_MSGS_MESSAGE_MANUALCONTROL_H


#include <string>
#include <vector>
#include <map>

#include "../std_msgs/Msg.h"

namespace mavros_msgs
{
struct ManualControl : Msg
{
  typedef ManualControl Type;

  ManualControl()
    : header()
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , r(0.0)
    , buttons(0)  {
    }
  ManualControl(const ManualControl& _alloc)
    : header()
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , r(0.0)
    , buttons(0)  {
  (void)_alloc;
    }



   typedef  Header  _header_type;
  _header_type header;

   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;

   typedef float _r_type;
  _r_type r;

   typedef uint16_t _buttons_type;
  _buttons_type buttons;





  typedef mavros_msgs::ManualControl* Ptr;
  typedef mavros_msgs::ManualControl* ConstPtr;

}; // struct ManualControl_

typedef ::mavros_msgs::ManualControl ManualControl;

typedef mavros_msgs::ManualControl* ManualControlPtr;
typedef mavros_msgs::ManualControl* ManualControlConstPtr;

// constants requiring out of line definition








} // namespace mavros_msgs


#endif // MAVROS_MSGS_MESSAGE_MANUALCONTROL_H
