// Generated by gencpp from file mavros_msgs/OverrideRCIn.msg
// DO NOT EDIT!


#ifndef MAVROS_MSGS_MESSAGE_OVERRIDERCIN_H
#define MAVROS_MSGS_MESSAGE_OVERRIDERCIN_H


#include <string>
#include <vector>
#include <map>

#include "../std_msgs/Msg.h"

namespace mavros_msgs
{
	class OverrideRCIn : public Msg
	{
	public:
		OverrideRCIn() : channels() {};
		OverrideRCIn(const OverrideRCIn& _alloc) : channels() {};

		std::vector<int> channels;

		typedef mavros_msgs::OverrideRCIn* Ptr;
		typedef mavros_msgs::OverrideRCIn* ConstPtr;
		typedef mavros_msgs::OverrideRCIn* OverrideRCInPtr;
		typedef mavros_msgs::OverrideRCIn* OverrideRCInConstPtr;

		std::ostream& operator<<(std::ostream& s)
		{
			return s;
		};
		bool operator==(const ::mavros_msgs::OverrideRCIn& rhs)
		{
			return this->channels == rhs.channels;
		};
		bool operator!=(const ::mavros_msgs::OverrideRCIn& rhs)
		{
			return !(*this == rhs);
		};

	}; // OverrideRCIn
} // namespace mavros_msgs


#endif // MAVROS_MSGS_MESSAGE_OVERRIDERCIN_H
