// Generated by gencpp from file mavros_msgs/RCIn.msg
// DO NOT EDIT!


#ifndef MAVROS_MSGS_MESSAGE_RCIN_H
#define MAVROS_MSGS_MESSAGE_RCIN_H


#include <string>
#include <vector>
#include <map>

#include "../std_msgs/Msg.h"

namespace mavros_msgs
{
	class RCIn : public Msg
	{
	public:

		RCIn() :rssi(0), channels() {};
		RCIn(const RCIn& _alloc) : rssi(0), channels() {};

		int rssi;
		std::vector<int> channels;

		typedef mavros_msgs::RCIn* Ptr;
		typedef mavros_msgs::RCIn* ConstPtr;
		typedef mavros_msgs::RCIn* RCInPtr;
		typedef mavros_msgs::RCIn* RCInConstPtr;




	}; // RCIn	
} // namespace mavros_msgs


#endif // MAVROS_MSGS_MESSAGE_RCIN_H
