// Generated by gencpp from file mavros_msgs/RCIn.msg
// DO NOT EDIT!


#ifndef MAVROS_MSGS_MESSAGE_RCIN_H
#define MAVROS_MSGS_MESSAGE_RCIN_H


#include <string>
#include <vector>
#include <map>

#include "../std_msgs/Msg.h"

namespace mavros_msgs
{

struct RCIn
{
  typedef RCIn Type;

  RCIn()
    : header()
    , rssi(0)
    , channels()  {
    }
  RCIn(const RCIn& _alloc)
    : header()
    , rssi(0)
    , channels()  {
  (void)_alloc;
    }



   typedef  Header  _header_type;
  _header_type header;

   typedef uint8_t _rssi_type;
  _rssi_type rssi;

   typedef std::vector<int>  _channels_type;
  _channels_type channels;





  typedef mavros_msgs::RCIn* Ptr;
  typedef mavros_msgs::RCIn* ConstPtr;

}; // struct RCIn_

typedef ::mavros_msgs::RCIn RCIn;

typedef mavros_msgs::RCIn* RCInPtr;
typedef mavros_msgs::RCIn* RCInConstPtr;

// constants requiring out of line definition









} // namespace mavros_msgs


#endif // MAVROS_MSGS_MESSAGE_RCIN_H
