// Generated by gencpp from file mavros_msgs/SetMode.msg
// DO NOT EDIT!


#ifndef MAVROS_MSGS_MESSAGE_SETMODE_H
#define MAVROS_MSGS_MESSAGE_SETMODE_H


#include "SetModeRequest.h"
#include "SetModeResponse.h"

#include "../std_msgs/Msg.h"

namespace mavros_msgs
{

struct SetMode : Msg
{

typedef SetModeRequest Request;
typedef SetModeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetMode
} // namespace mavros_msgs



#endif // MAVROS_MSGS_MESSAGE_SETMODE_H
