// Generated by gencpp from file mavros_msgs/SetModeResponse.msg
// DO NOT EDIT!


#ifndef MAVROS_MSGS_MESSAGE_SETMODERESPONSE_H
#define MAVROS_MSGS_MESSAGE_SETMODERESPONSE_H


#include <string>
#include <vector>
#include <map>




namespace mavros_msgs
{
    class SetModeResponse 
    {
    public:

        SetModeResponse() : mode_sent(false) {};
        SetModeResponse(const SetModeResponse& _alloc) : mode_sent(false) {};

        int mode_sent;

        typedef mavros_msgs::SetModeResponse* Ptr;
        typedef mavros_msgs::SetModeResponse* ConstPtr;
        typedef mavros_msgs::SetModeResponse* SetModeResponsePtr;
        typedef mavros_msgs::SetModeResponse* SetModeResponseConstPtr;

        std::ostream& operator<<(std::ostream& s)
        {
            return s;
        };
        bool operator==(const ::mavros_msgs::SetModeResponse& rhs)
        {
            return this->mode_sent == rhs.mode_sent;
        };
        bool operator!=(const ::mavros_msgs::SetModeResponse& rhs)
        {
            return !(*this == rhs);
        };
    }; // SetModeResponse
} // namespace mavros_msgs


#endif // MAVROS_MSGS_MESSAGE_SETMODERESPONSE_H
