// Generated by gencpp from file mavros_msgs/State.msg
// DO NOT EDIT!


#ifndef MAVROS_MSGS_MESSAGE_STATE_H
#define MAVROS_MSGS_MESSAGE_STATE_H


#include <string>
#include <vector>
#include <map>

#include "../std_msgs/Msg.h"

namespace mavros_msgs
{
	class State : public Msg
	{
	public:

		State() : Msg(), connected(false), armed(false), guided(false), manual_input(false), mode(), system_status(0) {};
		State(const State& _alloc) : Msg(), connected(false), armed(false), guided(false), manual_input(false), mode(), system_status(0) {};

		bool connected;
		bool armed;
		int guided;
		bool manual_input;
		std::string mode;
		int system_status;


		typedef mavros_msgs::State* Ptr;
		typedef mavros_msgs::State* ConstPtr;
		typedef mavros_msgs::State* StatePtr;
		typedef mavros_msgs::State* StateConstPtr;

		std::ostream& operator<<(std::ostream& s)
		{
			return s;
		};

	}; // State
} // namespace mavros_msgs


#endif // MAVROS_MSGS_MESSAGE_STATE_H
