// Generated by gencpp from file mavros_msgs/Thrust.msg
// DO NOT EDIT!


#ifndef MAVROS_MSGS_MESSAGE_THRUST_H
#define MAVROS_MSGS_MESSAGE_THRUST_H


#include <string>
#include <vector>
#include <map>


#include "../std_msgs/Msg.h"

namespace mavros_msgs
{
class Thrust : public Msg
{
public:
    Thrust() : thrust(0.0) {};
    Thrust(const Thrust& _alloc) : thrust(0.0) {};

    float thrust;

    typedef mavros_msgs::Thrust* Ptr;
    typedef mavros_msgs::Thrust* ConstPtr;
    typedef mavros_msgs::Thrust* ThrustPtr;
    typedef mavros_msgs::Thrust* ThrustConstPtr;

    std::ostream& operator<<(std::ostream& s)
    {
        return s;
    };
    bool operator==(const mavros_msgs::Thrust& rhs)
    {
        return this->thrust == rhs.thrust;
    };
    bool operator!=(const mavros_msgs::Thrust& rhs)
    {
        return !(*this == rhs);
    };
}; // Thrust
} // namespace mavros_msgs
#endif // MAVROS_MSGS_MESSAGE_THRUST_H
