// Generated by gencpp from file std_msgs/Empty.msg
// DO NOT EDIT!


#ifndef STD_MSGS_MESSAGE_EMPTY_H
#define STD_MSGS_MESSAGE_EMPTY_H


#include <string>
#include <vector>
#include <map>


namespace std_msgs
{
    class Empty
    {
    public:
        Empty() {};
        Empty(const Empty& _alloc) {};

        typedef std_msgs::Empty* Ptr;
        typedef std_msgs::Empty* ConstPtr;
        typedef std_msgs::Empty* EmptyPtr;
        typedef std_msgs::Empty* EmptyConstPtr;

        std::ostream& operator<<(std::ostream& s)
        {
            return s;
        };


    }; // class Empty
} // namespace std_msgs

#endif // STD_MSGS_MESSAGE_EMPTY_H
