// Generated by gencpp from file std_srvs/EmptyResponse.msg
// DO NOT EDIT!


#ifndef STD_SRVS_MESSAGE_EMPTYRESPONSE_H
#define STD_SRVS_MESSAGE_EMPTYRESPONSE_H


#include <string>
#include <vector>
#include <map>


namespace std_srvs
{
class EmptyResponse
{
public:

  EmptyResponse()
    {
    }
  EmptyResponse(const EmptyResponse& _alloc)
    {
    }






    std_srvs::EmptyResponse* Ptr;
    std_srvs::EmptyResponse* ConstPtr;
    std_srvs::EmptyResponse* EmptyResponsePtr;
    std_srvs::EmptyResponse* EmptyResponseConstPtr;

// constants requiring out of line definition



    std::ostream& operator<<(std::ostream& s)
    {
    return s;
    }


}; // class EmptyResponse
} // namespace std_srvs


#endif // STD_SRVS_MESSAGE_EMPTYRESPONSE_H
