// Generated by gencpp from file std_srvs/EmptyRequest.msg
// DO NOT EDIT!


#ifndef STD_SRVS_MESSAGE_EMPTYREQUEST_H
#define STD_SRVS_MESSAGE_EMPTYREQUEST_H


#include <string>
#include <vector>
#include <map>



namespace std_srvs
{
class EmptyRequest
{
public:

  EmptyRequest()
    {
    }
  EmptyRequest(const EmptyRequest& _alloc)
    {
    }






    std_srvs::EmptyRequest* Ptr;
    std_srvs::EmptyRequest* ConstPtr;
    std_srvs::EmptyRequest* EmptyRequestPtr;
    std_srvs::EmptyRequest* EmptyRequestConstPtr;

    std::ostream& operator<<(std::ostream& s)
    {
        return s;
    }

}; // class EmptyRequest
} // namespace std_srvs


#endif // STD_SRVS_MESSAGE_EMPTYREQUEST_H
