// Generated by gencpp from file std_srvs/Empty.msg
// DO NOT EDIT!


#ifndef STD_SRVS_MESSAGE_EMPTY_H
#define STD_SRVS_MESSAGE_EMPTY_H


#include "EmptyRequest.h"
#include "EmptyResponse.h"


namespace std_srvs
{

class Empty
{
EmptyRequest request;
EmptyResponse response;
}; // class Empty
} // namespace std_srvs

#endif // STD_SRVS_MESSAGE_EMPTY_H
