// Generated by gencpp from file geometry_msgs/Vector3.msg
// DO NOT EDIT!


#ifndef GEOMETRY_MSGS_MESSAGE_POSESTAMPED_H
#define GEOMETRY_MSGS_MESSAGE_POSESTAMPED_H


#include <string>
#include <vector>
#include <map>

#include "../std_msgs/Msg.h"

class Position
{
public:
    Position() : x(0.0), y(0.0), z(0.0) {};

    double x;
    double y;
    double z;
};

class Pose
{
public:
    Position position;

};




namespace geometry_msgs
{
    class PoseStamped : public Msg
    {
    public:
        PoseStamped() {};
        PoseStamped(const PoseStamped& _alloc) {};

        Pose pose;

        static geometry_msgs::PoseStamped* Ptr;
        typedef geometry_msgs::PoseStamped* ConstPtr;
        static geometry_msgs::PoseStamped* Vector3Ptr;
        static geometry_msgs::PoseStamped* Vector3ConstPtr;

        std::ostream& operator<<(std::ostream& s)
        {
            return s;
        };
        bool operator==(const ::geometry_msgs::PoseStamped& rhs)
        {
            return this->pose.position.x == rhs.pose.position.x &&
                this->pose.position.y == rhs.pose.position.y &&
                this->pose.position.z == rhs.pose.position.z;
        };
        bool operator!=(const ::geometry_msgs::PoseStamped& rhs)
        {
            return !(*this == rhs);
        };
    }; // PoseStamped
} // namespace geometry_msgs


#endif // GEOMETRY_MSGS_MESSAGE_POSESTAMPED_H
