// Generated by gencpp from file geometry_msgs/Quaternion.msg
// DO NOT EDIT!


#ifndef GEOMETRY_MSGS_MESSAGE_QUATERNION_H
#define GEOMETRY_MSGS_MESSAGE_QUATERNION_H


#include <string>
#include <vector>
#include <map>


#include "../std_msgs/Msg.h"

namespace geometry_msgs
{
    class Quaternion : public Msg
    {
    public:
        Quaternion() : x(0.0), y(0.0), z(0.0), w(0.0) {};
        Quaternion(const Quaternion& _alloc) : x(0.0), y(0.0), z(0.0), w(0.0)  { (void)_alloc; };

        double x;
        double y;
        double z;
        double w;

        static geometry_msgs::Quaternion* Ptr;
        typedef geometry_msgs::Quaternion* ConstPtr;
        static geometry_msgs::Quaternion* QuaternionPtr;
        static geometry_msgs::Quaternion* QuaternionConstPtr;

        std::ostream& operator<<(std::ostream& s)
        {
            return s;
        };
        bool operator==(const ::geometry_msgs::Quaternion& rhs)
        {
            return this->x == rhs.x &&
                this->y == rhs.y &&
                this->z == rhs.z &&
                this->w == rhs.w;
        };
        bool operator!=(const ::geometry_msgs::Quaternion& rhs)
        {
            return !(*this == rhs);
        };
    }; // Quaternion
} // namespace geometry_msgs


#endif // GEOMETRY_MSGS_MESSAGE_QUATERNION_H
