// Generated by gencpp from file geometry_msgs/Twist.msg
// DO NOT EDIT!


#ifndef GEOMETRY_MSGS_MESSAGE_TWIST_H
#define GEOMETRY_MSGS_MESSAGE_TWIST_H


#include <string>
#include <vector>
#include <map>

#include <geometry_msgs/Vector3.h>

namespace geometry_msgs
{
class Twist
{
public:

    Twist()
        : linear()
        , angular() {
    };
  Twist(const Twist& _alloc)
      : linear()
      , angular() {
  };



   Vector3 linear;
   Vector3 angular;




    typedef geometry_msgs::Twist* Ptr;
    typedef geometry_msgs::Twist* ConstPtr;
    typedef geometry_msgs::Twist* TwistPtr;
    typedef geometry_msgs::Twist* TwistConstPtr;



    std::ostream& operator<<(std::ostream& s)
    {
        return s;
    };

}; // class Twist
} // namespace geometry_msgs

#endif // GEOMETRY_MSGS_MESSAGE_TWIST_H
